---
abstract: 'automate launching of fake mdp for testing purposes'
author:
  - 'Jerome Quelin'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Corpus-Audio-MPD
provides:
  Test::Corpus::Audio::MPD:
    file: lib/Test/Corpus/Audio/MPD.pm
    version: 1.111260
requires:
  Exporter: 0
  File::Copy: 0
  File::ShareDir::PathClass: 0
  File::Temp: 0
  Path::Class: 0
  Readonly: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Corpus-Audio-MPD
  homepage: http://search.cpan.org/dist/Test-Corpus-Audio-MPD/
  repository: git://github.com/jquelin/test-corpus-audio-mpd.git
  x_MailingList: http://groups.google.com/group/audio-mpd
version: 1.111260
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@Filter/AutoVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Filter/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Filter/PruneFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Filter/AutoPrereqs'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.17
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git::Check'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git::Commit'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Filter/Git::CommitBuild'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/TagMaster'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/TagRelease'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git::Push'
      version: 1.110500
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200004
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200004
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200004
